### PR TITLE
update_results.py: Add specifying board to update or `all`, help message

### PR DESCRIPTION
**Pull request by philipandag**
Added a help message and option to update only one selected board directory

### CODE REVIEW

**Comment by miczyg1** [comment]
Created the `boards/Protectli/VP66xx/results.csv` with `Test name,Test ID,VP66x0 VP6650 v0.9.0,VP66x0 VP6670 v0.9.0` in the first row as per README, issued `python update_results.py VP66xx` and I got:

```
python update_results.py VP66xx
-- Downloading: https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/export?format=csv&gid=736501945#gid=736501945
-- Updating: /home/miczyg/Projects/Dasharo/osfv-results/boards/Protectli/VP66xx/results.csv
Traceback (most recent call last):
  File "/home/miczyg/Projects/Dasharo/osfv-results/update_results.py", line 107, in <module>
    main()
  File "/home/miczyg/Projects/Dasharo/osfv-results/update_results.py", line 102, in main
    update_results_there(table, data_from_matrix)
  File "/home/miczyg/Projects/Dasharo/osfv-results/update_results.py", line 37, in update_results_there
    selected = data_from_matrix[columns]
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/miczyg/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miczyg/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/miczyg/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['VP66x0 VP6650 v0.9.0', 'VP66x0 VP6670 v0.9.0'] not in index"
```

There is no column with v0.9.0 results in the google sheet. So how it was generated in https://github.com/Dasharo/osfv-results/pull/6 ?

**Comment by miczyg1** [comment]
When added `-rc7` suffix the script worked, probably as intended.

**Review by miczyg1 — APPROVED** [review]

**Comment by philipandag** [comment]
There is no `VP66x0 VP6650 v0.9.0` or `VP66x0 VP6670 v0.9.0` in the matrix. RC7 is the latest version.

**Comment by miczyg1** [comment]
> There is no `VP66x0 VP6650 v0.9.0` or `VP66x0 VP6670 v0.9.0` in the matrix. RC7 is the latest version.

Then what is this? https://github.com/Dasharo/osfv-results/pull/6/files#diff-1b63c0b8899f3331743d48ae393b810c41e045ec5f13c867f0a1e6904d694d0cR1

**Comment by philipandag** [comment]
> Then what is this?

I have changed the header after reading the results from the matrix. I think we are not always including full release versions in the matrix as they are just renamed RC versions. The columns in other boards directories also don't always translate directly to the test matrix, that's why I changed them here. At this moment this repository is not consistent, even before this release PR. Maybe we should decide and say in the README how exactly it should look, including the file structure and file contents. 

The script was created before the release files for NVC laptops were renamed to `<version>-results.md` from just `results.md` so that's also a new situation.

I think a there would be a couple of options for good and consistent structure of this repository:
- Keep all releases for a board in a single file, differentiate them only using the column headers. It's how I originally thought this repo would look like and that's what the script expects. In this case all results are always updated by the script and column names translate directly to columns in the test matrix. Old releases don't become immutable. If the matrix changes, so do the files here. This option may become messy if different releases have different test scopes because then if just one release has some test performed all the other releases would have "NOT TESTED" or "SKIP" values copied here from the matrix.
- Keep the releases in seperate files. If so:
    - Update the script so that it manages all the releases for a given platform. Possibly it could look for the newest RC and use it for the release.
    - Use a workflow for adding a new release like this: create a file, fill it like the README now says, then rename it when the results are ready to be published and the script will ignore them.

**Comment by miczyg1** [comment]
My question was about why there is v0.9.0 in the field I linked. But I already got the answer elsewhere that RC7 results were just copied and renamed to non-RC

**Pull request merged**
