### PR TITLE
Scripts for updating results

### PR DESCRIPTION
**Pull request by philipandag**

### CODE REVIEW

**Comment by philipandag** [comment]
Those are not good quality, but they still might be useful

**Comment by macpijan** [comment]
@philipandag Thanks, can you elaborate a bit more on how you used these scripts to simplify the workflow? I can see 3 very similar scripts, how they should be executed?

**Comment by philipandag** [comment]
I didn't put much thought into the script, it's just a quick prototype I made so I didn't have to copy the results manually. I should have probably marked it as a draft. Anyway:

By using the scripts you only need to run the `update_results.py` in the main directory to update all the results in the repository. To make it happen every directory that contains a `results.csv` file needs to have a duplicate of `boards/.../update_results.py`. The outside script is very different from those that can be found in `boards` directory so the names should probably be changed.

* The script in the root directory downloads the test matrix and then executes any scripts found in the `boards` directory. 
* The scripts in the directories containing `results.csv`, when called by the main script, use the downloaded matrix to update the 'results.csv`file in the directory they are located in. 
* The platforms which should be included in the results file are determined by changing the 'models' list directly in that directories script.
* To add a new directory with `results.csv` and have it updated by the main script you need to copy a script from another existing directory and change the content of `models` list to match the platform IDs you want from the matrix.

If I were to improve the scripts first I would make them into only one script in the main directory which traverses `boards` directory and updates the results by reading some configuration file with names of platforms to include or alternatively by reading the column names from already existing `results.csv`.

**Comment by mkopec** [comment]
I think it's okay to merge, but could you add some basic instructions on how to use these to the README @philipandag ?

**Comment by philipandag** [comment]
Sure @mkopec. Should I also try to improve the script in any way? Like giving the instructions as a `-h` option? Or is it fine as it is? Also the script at this moment doesn't ignore results like `NOT TESTED` which should not be included.

**Comment by mkopec** [comment]
> Also the script at this moment doesn't ignore results like NOT TESTED which should not be included.

Let's try to address this feature at least, IMO adding a -h option is not strictly necessary as long as we have something in the README

**Comment by philipandag** [comment]
@mkopec The results.csv file shows results for multiple boards at the same time. Sometimes one board has `NOT TESTED` and the other one has an actual test result. Should the script only exclude the tests which are empty in all the boards?

**Comment by mkopec** [comment]
> Should the script only exclude the tests which are empty in all the boards?

Exactly @philipandag , if it's tested on at least one variant then it should be included

**Comment by philipandag** [comment]
@mkopec I made the script not include empty results and refactored it so that adding new boards won't be as silly as before. I think it is ready.

**Review by mkopec — APPROVED** [review]
Thanks

**Pull request merged**
